folder: /home/user2/tst
count_file: 5
size_file: 1
size_name_file: 5
folder_log: /home/user/PycharmProjects/pythonProject
type: zip

local_path: /home/user
remoute_path: /home/user2
host: 0.0.0.0
user: user2

folder_log2: /home/user/PycharmProjects/pythonProject
date1: 2023-08-27 12:00:00
date2: 2023-08-27 19:30:00